//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ApplicationCore.Properties.ResourceEN", typeof(ResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add data successfully.
        /// </summary>
        public static string AddComplete {
            get {
                return ResourceManager.GetString("AddComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data empty.
        /// </summary>
        public static string DataEmpty {
            get {
                return ResourceManager.GetString("DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data successfully.
        /// </summary>
        public static string DeleteComplete {
            get {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Duplicate.
        /// </summary>
        public static string ErrorDevMsgDuplicate {
            get {
                return ResourceManager.GetString("ErrorDevMsgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information cannot be empty.
        /// </summary>
        public static string ErrorDevMsgRequire {
            get {
                return ResourceManager.GetString("ErrorDevMsgRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred! Please contact MISA!.
        /// </summary>
        public static string ErrorUserMsgExeption {
            get {
                return ResourceManager.GetString("ErrorUserMsgExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data please check again!.
        /// </summary>
        public static string ErrorUserMsgValidate {
            get {
                return ResourceManager.GetString("ErrorUserMsgValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid data.
        /// </summary>
        public static string MsgIsValid {
            get {
                return ResourceManager.GetString("MsgIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command runs successfully but cannot be added to the database! Please double check the Insert statement.
        /// </summary>
        public static string NoAddInDataBase {
            get {
                return ResourceManager.GetString("NoAddInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cannot delete data! Please double check the Delete statement or upload data.
        /// </summary>
        public static string NoDeleteInDataBase {
            get {
                return ResourceManager.GetString("NoDeleteInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command runs successfully but cannot update to the database! Please check the Update statement again.
        /// </summary>
        public static string NoUpdateInDataBase {
            get {
                return ResourceManager.GetString("NoUpdateInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit data successfully.
        /// </summary>
        public static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
    }
}
